### ISSUE TITLE
[Feature] Include a Twig Extension to retrieve all Jasmine tests from Bundles

### ISSUE THREAD

**Issue by relaxnow** [havvg/HavvgJasmineBundle#1]
I don't want to separate my JavaScript functionality (which is in various bundles under Resources/public/js) from my Jasmine specs, instead I want to place them in Resources/js/spec/ and have all tests from the enabled bundles loaded when I go to the runner.

**Comment by havvg** [comment]
Current master allows the usage of bundle specific spec files.

The default location of such files: `BundlePath/Resources/jasmine/specs/`
To use a custom location, simple implement the `Havvg\Bundle\JasmineBundle\JasmineSpecAwareBundleInterface` with your bundle.

To include the spec files in the template:

``` html+jinja
    {% javascripts
        filter="?yui_js"
        output="js/specs.js"
        '@havvg_jasmine_specs_js'
    %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
```

This will combine every spec asset from all enabled bundles.
